##### Students
GET http://localhost:8080/academics/api/students/all
Accept: application/json

### Create Student
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
  "email": "johndoe@mail.com",
  "name": "John Doe",
  "username": "ivoafonsobispo",
  "password": "jd",
  "courseCode": 9119
}

##### Courses
GET http://localhost:8080/academics/api/courses/all
Accept: application/json

### Add Course
POST http://localhost:8080/academics/api/courses
Content-Type: application/json

{
  "code": 3,
  "name": "New Course Clean Code"
}

##### Student Details
GET http://localhost:8080/academics/api/students/ivoafonsobispo
Accept: application/json

##### Student Subjects
GET http://localhost:8080/academics/api/students/ivoafonsobispo/subjects
Accept: application/json

##### Subjects
GET http://localhost:8080/academics/api/subjects/all
Accept: application/json

##### Specific Subject
GET http://localhost:8080/academics/api/subjects/1
Accept: application/json

##### Subject Students
GET http://localhost:8080/academics/api/subjects/1/students
Accept: application/json

##### Teachers
GET http://localhost:8080/academics/api/teachers/all
Accept: application/json

##### Associate Subject to Teacher
POST http://localhost:8080/academics/api/teachers/mariajoana/2
Content-Type: application/json

##### GET Teacher Subjects
GET http://localhost:8080/academics/api/teachers/mariajoana/subjects
Accept: application/json

##### GET Subject Teachers
GET http://localhost:8080/academics/api/subjects/1/teachers
Accept: application/json

### Create Teacher
POST http://localhost:8080/academics/api/teachers
Content-Type: application/json

{
  "email": "ivo@mail.pt",
  "name": "Ivo Bispo",
  "office": "L-33",
  "password": "ivoivo",
  "username": "ivoafobispo"
}

##### Find Teacher
GET http://localhost:8080/academics/api/teachers/ivoafobispo
Content-Type: application/json

##### Update Teacher
PUT http://localhost:8080/academics/api/teachers/ivoafobispo
Content-Type: application/json

{
  "email": "ivo@mail.pt",
  "name": "Jose Areia",
  "office": "L-33",
  "password": "ivoivo",
  "username": "ivoafobispo"
}

##### Delete Teacher
DELETE http://localhost:8080/academics/api/teachers/ivoafobispo
Content-Type: application/json

##### Update Student
PUT http://localhost:8080/academics/api/students/ivoafonsobispo
Content-Type: application/json

{
  "email": "ivo@mail.pt",
  "name": "Ivo Bispo Alterado",
  "office": "L-33",
  "password": "ivoivo",
  "courseCode": 9119
}


